apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast-microprofile-statefulset
  labels:
    app: hazelcast-microprofile
spec:
  replicas: 2
  serviceName: hazelcast-microprofile-service
  selector:
    matchLabels:
      app: hazelcast-microprofile
  template:
    metadata:
      labels:
        app: hazelcast-microprofile
    spec:
      containers:
        - name: hazelcast-microprofile-container
          image: openliberty-hazelcast-microprofile:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5701
          - containerPort: 9080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-microprofile-service
spec:
  type: NodePort
  selector:
    app: hazelcast-microprofile
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
      nodePort: 31000
